apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: ghcr.io/YOUR_GITHUB_USER/ml-tracker-api
    newTag: latest
  - name: ghcr.io/YOUR_GITHUB_USER/ml-tracker-frontend
    newTag: latest
