apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: ghcr.io/tabrez05/model-observer-api
    newTag: latest
  - name: ghcr.io/tabrez05/model-observer-frontend
    newTag: latest
