apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# Scale down for local minikube
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: frontend

images:
  - name: ghcr.io/tabrez05/model-observer-api
    newTag: dev
  - name: ghcr.io/tabrez05/model-observer-frontend
    newTag: dev
